import type { FunctionContext, GenerationProvider } from "./types"

export class MockGenerationProvider implements GenerationProvider {
  async generateFunction(
    functionName: string,
    _context: FunctionContext
  ): Promise<{ code: string } | null> {
    return {
      code: generatePlaceholder(functionName),
    }
  }

  async repairFunction(
    _functionName: string,
    implementation: string,
    _errorMessage: string,
    _attempt: number
  ): Promise<{ code: string } | null> {
    return { code: implementation }
  }
}

function generatePlaceholder(functionName: string): string {
  return `export function ${functionName}(...args: unknown[]): unknown {
  // TODO: generated by Aigen
  return args
}`
}
